### ISSUE TITLE
Wrong sheet for CPP02

### ISSUE THREAD

**Issue by iuryr** [rphlr/42-Evals#10]
Hello!

The sheet for CPP02 in the website is actually the sheet for CPP01 project (https://www.42evals.com/sheets/66ba2f33f5f533faca2c44c5) and there is no sheet for CPP02 project in sheets list (at least, I could not find it).

**Comment by rphlr** [comment]
Hello!

The title for CPP02 has been updated and the correct page for CPP01 is now available at this link: [CPP01 Page](https://www.42evals.com/sheets/66ba2f33f5f533faca2c44c5).

Thank you for catching that!

**Comment by iuryr** [comment]
Hi @rphlr , thank you for the prompt reply! But I'm afraid the link you posted above still points to a CPP01 eval sheet...

**Comment by rphlr** [comment]
Thanks for pointing that out! You're absolutely right. I've just updated the link now: https://www.42evals.com/sheets/66c35fc8de323ff257d79787 😊
