### ISSUE TITLE
Typo section name in CPP Module 00

### ISSUE THREAD

**Issue by SrVariable** [rphlr/42-Evals#15]
**Describe the bug**
As stated in the title, there is a typo, it shows `Prerequisites<br>Suspected Cheating`

**To Reproduce**
1. Go to '[CPP Module 00](https://www.42evals.com/sheets/66ba2ca0704e70e26562d311)'
2. Scroll down to 'Mandatory Part'
3. See error 

**Expected behavior**
I believe it should only be **Prerequisites** to follow the same section names as other CPP Modules.

**Screenshots**
![image](https://github.com/user-attachments/assets/2e5b9b32-0855-4388-9247-d9442f624421)

**Desktop (please complete the following information):**
 - OS: Debian 12 (bookworm)
 - Browser Brave Browser
 - Version 1.68.128 Chromium: 127.0.6533.73

**Comment by rphlr** [comment]
Thank you! The typo has been corrected. :-)
