### ISSUE TITLE
42Evals Website password :(

### ISSUE THREAD

**Issue by FrancoisCardinaud** [rphlr/42-Evals#4]
I've been trying to figure out the enigma of the new 42Evals website password, to no avail...
Does a kind soul have an extra clue I could use to figure it out?

**Comment by rphlr** [comment]
CVb3d2023 ;)

**Comment by rphlr** [comment]
Hello, yes of course! Look at the source code of my profile README.md, if you still can't get the password, simply write an email to 42-evals@gmx.ch to get the code 😊

**Comment by FrancoisCardinaud** [comment]
Thanks a lot for your help!!

**Comment by FrancoisCardinaud** [comment]
Thanks a lot for your kind help!
    Le mercredi 24 janvier 2024 à 15:19:42 UTC+1, Raphael ***@***.***> a écrit :  
 
 


CVb3d2023 ;)

**Comment by coincoin94360** [comment]
Hi, someone can help me to find the password. I follow all the comment in source page : . I search in all source code of the 42-Evals repository but nothing obvious for me. Couldyou please help me ? Thank you
