### ISSUE TITLE
Pipex eval sheet missing

### ISSUE THREAD

**Issue by yas0nia** [rphlr/42-Evals#5]
Hi! I see the eval sheet (in French) in source files, but it leads to 404 not found on ur website :(

**Comment by rphlr** [comment]
Hello! That's odd, but thank you for pointing it out! I accidentally updated the link incorrectly. The correct path is "https://42evals.com/Cursus/pipex," not "https://42evals.com/Cursus/Pipex" as I previously did. Access has now been restored. :)
