### ISSUE TITLE
Site completly broken on Mozilla Firefox on Linux

### ISSUE THREAD

**Issue by veliga-syutkin** [rphlr/42-Evals#9]
On sign in try with good credentials the site comes back to login page. Already sent a report to Mozilla via built-in tool. 

If you want additional info from my system in order to try to fix, please ask what info you need.

Best regards,

**Comment by rphlr** [comment]
Hey! Sorry for the trouble. I just noticed that the bug appears not only on Firefox but also on other web browsers. I removed the password identification for now because a new app that follows the 42 guidelines is coming (very) soon.
